### ISSUE TITLE
Shadow colors cannot be set

### ISSUE THREAD

**Issue by stefonarch** [timgott/wayfire-shadows#16]
With any value I try in `wayfire.ini` I get this message, even with the default value. Maybe I'm missing something. Latest git.

```
353 [winshadows]
354 include_undecorated_views = true
355 shadow_color = #00000070
356 shadow_radius = 50
357 vertical_offset = 10
358 horizontal_offset = 5
```

```
`journalctl`

`mar 04 08:07:09 wayfire[938000]: EE 04-03-23 08:07:09.567 - [src/file.cpp:340] Error in file /home/stef/.config/lxqt-wayland/wayfire.ini:355, invalid option value!
`

**Comment by timgott** [comment]
I think you have to add a backslash before the # symbol, otherwise wayfire treats it is a comment.

btw, I'd suggest you to use wcm to configure this plugin, it will be easier. I wrote the metadata to work well with wcm.

**Comment by stefonarch** [comment]
Thought I'd tested backlash too -  anyway like that it works.
` shadow_color = \#A51D2DFF`

**Comment by timgott** [comment]
Do you really want shadows in that color or was that just an example?

If yes I'd like to see a screenshot 😄

**Comment by stefonarch** [comment]
No, this was for testing :)
