### ISSUE TITLE
Shadows do not appear

### ISSUE THREAD

**Issue by BowlBird** [timgott/wayfire-shadows#18]
Hello! I'm currently experiencing a problem where no matter what I do, shadows do not appear. I've tried both client side and server side decoration, enabled and disabled the decorations plugin, added wayfire-plugins-extra and tried without, tried different versions of wayfire altogether (I'm currently using the July 30th, 2023 git branch), etc.

Still however, shadows and glow never work. I've never gotten it to work no matter the config. Is there some dependency needed or config I'm missing?

**Comment by timgott** [comment]
You can test it using one of the configs in the testconfig folder with `wayfire --config ...`.

Check the output for errors and whether the plugin was found correctly.

**Comment by BowlBird** [comment]
Hello again, what ended up happening is when I built using meson, I needed to use the 
```
--prefix=/usr
```
option to make sure it went into my /usr/lib/wayfire plugin folder, got it working.

There is another problem though, for some applications like kitty (terminal emulator), the shadows only apply once the window is moved. for others like firefox, the shadows never appear. Any idea why?

**Comment by timgott** [comment]
Ah yes, that was the signal issue that I meant, see the edit above. I don't remember the details but I had a discussion about it on the wayfire IRC a month ago and haven't worked on it since then.

**Comment by BowlBird** [comment]
That seemed to fix everything, I'll keep an eye out for future updates as well. Thanks so much!
