### ISSUE TITLE
Compilation Failure & Memory Leak

### ISSUE THREAD

**Issue by tsujan** [timgott/wayfire-shadows#6]
Thanks for the plugin!

I found two problems:
1. The plugin can't be compiled against Wayfire 0.7.4. The fix is easy: `#include <wayfire/region.hpp>` should be removed from `deco-shadow.hpp`.
2. There's a great memory leak when opening and closing windows that have shadow. It can be fixed by adding a d-tor to the class `wf::windecor::decoration_shadow_t`:

```c++
wf::windecor::decoration_shadow_t::~decoration_shadow_t() {
    OpenGL::render_begin();
    program.free_resources();
    OpenGL::render_end();
}
```

**Comment by tsujan** [comment]
Oh, it seems that the plugin is intended for use with *git* Wayfire, not its latest release. If so, please ignore 1 — I use the release.

**Comment by timgott** [comment]
Yes the master branch targets the git version and there is the backport0.7 branch for the stable release, which I tried to convey in the Readme. l can probably make that a bit more clear.

**Comment by tsujan** [comment]
> which I tried to convey in the Readme.

Yes, it was my mistake.

However, 2 still holds.

**Comment by timgott** [comment]
Not anymore :smile:

I rewrote the README a bit to address 1 and merged the focus glow branch and fixed the memory leak there, as well as some other remaining issues it had while I was at it, so there is actually a major new feature in the main branch too.

**Comment by tsujan** [comment]
Thanks for the quick reply and action!
