### ISSUE TITLE
master branch fails to build with wayfire-git

### ISSUE THREAD

**Issue by akliuxingyuan** [timgott/wayfire-shadows#7]
http://ix.io/4g8B

**Comment by NamorNiradnug** [comment]
It complies now, but shadow is offset from the window.
![screenshot_2022-11-18-111831](https://user-images.githubusercontent.com/50048443/202654579-4bf722b3-7e05-4089-9b2a-f3bc18b9c138.png)

There is no offset while moving or resizing the window.

**Comment by NamorNiradnug** [comment]
> Is the offset constant or does it depend on the window position? e.g., if you move the window to the top left corner, is the offset of the shadow relative to the window still the same?

It depends on position
Closer to left top the offset is less

**Comment by timgott** [comment]
That's what you get if you try to find the right offsets by trial and error :sweat_smile:

Should be fixed now.
