### ISSUE TITLE
no file region.hpp

### ISSUE THREAD

**Issue by boris3812** [timgott/wayfire-shadows#8]
when compliling 
ninja -C build && sudo ninja -C build install

[1/5] Compiling C++ object libwinshadows.so.p/shadow-surface.cpp.o
FAILED: libwinshadows.so.p/shadow-surface.cpp.o 
c++ -Ilibwinshadows.so.p -I. -I.. -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/libevdev-1.0 -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -std=c++17 -O3 -DWLR_USE_UNSTABLE -DWAYFIRE_PLUGIN -fPIC -pthread -MD -MQ libwinshadows.so.p/shadow-surface.cpp.o -MF libwinshadows.so.p/shadow-surface.cpp.o.d -o libwinshadows.so.p/shadow-surface.cpp.o -c ../shadow-surface.cpp
In file included from ../shadow-surface.hpp:13,
                 from ../shadow-surface.cpp:1:
../deco-shadow.hpp:4:10: fatal error: **wayfire/region.hpp: no such file or directory**
    4 | #include <wayfire/region.hpp>

**Comment by timgott** [comment]
Read the :warning: in the Readme first please
