### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by UltraBlackLinux** [timgott/wayfire-shadows#9]
Hey there,
I really like this plugin, though I'm not a big fan of installing stuff directly from source as I tend to lose track of these files over time.
Could you create an aur package for this (Or maybe for lure?)
Thanks!

**Comment by timgott** [comment]
I don't use those systems, but please create packages for anything you like if you can. I agree that building from source is not practical for most users.

It should be easy to write a build script for any package manager where wayfire is packaged. Compare how wayfire-plugins-extra is packaged if in doubt. The winshadows plugin does not have any dependencies except Wayfire.

Personally I currently ninja install from source in a distrobox container only for development and testing. For daily use on the host system, I create rpm packages (using a .spec file and rpmbuild).

**Comment by UltraBlackLinux** [comment]
I've never maintained any package and I doubt I will be good at it. I could create a pkgbuild but where is the fun in a package that does not update once a new version is available

**Comment by timgott** [comment]
For now there has never been a release anyways and I don't think there will be one at least until Wayfire itself becomes more stable.

**Comment by UltraBlackLinux** [comment]
> For now there has never been a release anyways and I don't think there will be one at least until Wayfire itself becomes more stable.

It's not really about the releases but rather about the commits. You want to update git-based packages on a per-commit basis

**Comment by timgott** [comment]
Don't the ...-git packages on AUR do that without any maintenance? Otherwise I don't understand what you mean by 

> but where is the fun in a package that does not update once a new version is available

**Comment by UltraBlackLinux** [comment]
they don't. While many PKGBUILDs support getting the version from e.g. git, but you still need a version update to initiate a package update when updating them via the package manager
